# Generated by Django 4.2.1 on 2023-05-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('id_number', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('available_vacation_days', models.IntegerField()),
                ('approved_vacation_days', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='Employee',
            name='id_number',
            field=models.CharField(max_length=255),
        ),
    ]
