# Generated by Django 4.2.1 on 2023-05-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_vacationrequest_alter_employee_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.IntegerField(unique=True),
        ),
    ]
